apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
    spec:
      containers:
        - name: SERVICE_NAME
          image: SERVICE_IMAGE
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
